
@url = http://127.0.0.1:5000/api/customers
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2IwYTYyYzQ3OWQxNzk1YzhhZjIwOCIsImlhdCI6MTY5ODM2ODkwNCwiZXhwIjoxNzAwOTYwOTA0fQ.FlBm3zs8mfh2EIAOWEDzcx23hg8KNv7lVyauxiEWg2k

### registrar cliente
POST {{url}}
Content-Type: application/json

{
    "name": "prueba",
    "email": "prueba@prueba16.com",
    "password": "123456"
}

### loguear cliente
POST {{url}}/login
Content-Type: application/json

{
    "email": "prueba@prueba13.com",
    "password": "123456"
}

### obtener el perfil del cliente
GET {{url}}/profile
Authorization: Bearer {{token}}

### actualizar perfil del cliente
PUT {{url}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "prueba dsfs",
    "email": "prueba@prueba13.com",
    "password": "123456"
}
