@url = http://127.0.0.1:5000/api/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2FlMDc2ZDZjMmY5YzRkZTE1MGIxNyIsImlhdCI6MTY5ODM1ODQ3NiwiZXhwIjoxNzAwOTUwNDc2fQ.l6wSswoCPKhn15LEFSyPV3IKU2wiLPl1DCcV_L6Z8iQ


### login de usuario
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123456"
}

### registrar usuario
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "usuario",
    "email": "usuario1@usuario.com",
    "password": "123456"
}

### obtener el perfil del usuario
GET {{url}}/profile
Authorization: Bearer {{token}}
